Sabrina branch
brucker3/CS5551 pull request #11
Opened 2020-09-20 20:34 UTC by brucker3

2020-09-21 21:59 UTC, zealpatel1990 requested changes
How can I exclude myenv directory from approval or merging with the master? Or do Sabrina have to do another pull request?

2020-09-21 22:05 UTC, brucker3 commented
> How can I exclude myenv directory from approval or merging with the master? Or do Sabrina have to do another pull request?

is myenv your python virtual enviroment?
I added mine to the gitignore file. you can find it in the proejct rout directory is ls -a

2020-09-24 17:11 UTC, brucker3 commented on checkers/manage.py
> +#!/usr/bin/env python
this file is not needed it exist at the root layer mysite

2020-09-24 17:12 UTC, brucker3 commented on checkers/checkers/settings.py
> +"""
this file looks good but I'm confused why its in another checkers folder?

2020-09-24 17:13 UTC, brucker3 commented on checkers/baseapp/models.py
> +from django.db import models
what is the directory baseapp/? it looks like this code should be in mysite/checkers/modelrs.py

2020-09-27 21:48 UTC, brucker3 commented
this pr is no longer needed

2020-09-27 21:48 UTC, closed without merging